export const recipes= [
    {icon_name: "Homard",
     name: "Homard en chaud froid",
     image: require("../assets/homardRecette.png"),
     image_icon: require("../assets/homardRecette_icon.png"),
     description: ["Faites cuire les homards dans de l'eau bouillante avec du thym,",
                " du laurier, du sel et du poivre de Cayenne.",
                "Laissez cuire 20 minutes. Egouttez-les et laissez-les refroidir.",
                "",
                "Découpez les coffres des homards dans le sens de la longueur.",
                "",
                "Mélangez la mayonnaise avec le cognac, le corail et la ciboulette ciselée."
            ]
    },
    {icon_name: "St Jacques",
     name: "Noix de Saint-Jacques flambées au cognac",
     image: require("../assets/saintJacques.png"),
     image_icon: require("../assets/saintJacques_icon.png"),
     description: ["Faire fondre du beurre avec des échalotes puis ajouter les noix de Saint-Jacques.",
                " Les faire revenir en laissant le milieu translucide puis les retirer du feu",
                "",
                "Ajouter l'ail et le persil dans la poêle et laisser cuire quelques secondes.",
                " Bien faire chauffer la poêle, puis flamber au Cognac. Une fois la flamme éteinte,",
                " ajouter les noix de Saint-Jacques (Il ne faut pas les flamber car elles perdent leur saveur).",
                "",
                "Déguster chaud nature ou accompagné d'une fondue de poireaux."
            ]
    },
    {icon_name: "Bar",
     name: "Bar rôti au laurier frais",
     image: require("../assets/barRecette.png"),
     image_icon: require("../assets/barRecette_icon.png"),
     description: ["Sur une plaque ou un plat allant au four,",
                " déposer quelques feuilles de laurier frais,",
                " verser un filet d'huile d'olive et du gros sel.",
                " Déposer le bar, puis l'arroser d'un filet d'huile d'olive",
                " et mettre un peu de gros sel sur la peau.",
                "",
                "Cuire au four pendant 12 min à 240°C."
            ]
    },
    {icon_name:"Tourteau",
     name: "Tourteau linguine",
     image: require("../assets/poulpe.png"),
     image_icon: require("../assets/poulpe.png"),
     description: ["XXX YYY ZZZ",
                "",
                "",
                "",
                "Qu'il est chaud le soleil",
                "Quand nous sommes en vacances",
                "Y a d'la joie, des hirondelles",
                "C'est le sud de la France",
                "Papa bricole au garage",
                "Maman lit dans la chaise longue",
                "Dans ce joli paysage",
                "Moi, je me balades en tongs",
                "",
                "Que de bonheur!",
                "Que de bonheur!"
            ]
    },
    {icon_name:"Recette",
     name: "Recette XYZ",
     image: require("../assets/poulpe.png"),
     image_icon: require("../assets/poulpe.png"),
     description: ["XXX YYY ZZZ",
                "",
                "",
                "",
                "Qu'il est chaud le soleil",
                "Quand nous sommes en vacances",
                "Y a d'la joie, des hirondelles",
                "C'est le sud de la France",
                "Papa bricole au garage",
                "Maman lit dans la chaise longue",
                "Dans ce joli paysage",
                "Moi, je me balades en tongs",
                "",
                "Que de bonheur!",
                "Que de bonheur!"
            ]
    },
    {icon_name:"Recette",
     name: "Recette XYZ",
     image: require("../assets/poulpe.png"),
     image_icon: require("../assets/poulpe.png"),
     description: ["XXX YYY ZZZ",
                "",
                "",
                "",
                "Qu'il est chaud le soleil",
                "Quand nous sommes en vacances",
                "Y a d'la joie, des hirondelles",
                "C'est le sud de la France",
                "Papa bricole au garage",
                "Maman lit dans la chaise longue",
                "Dans ce joli paysage",
                "Moi, je me balades en tongs",
                "",
                "Que de bonheur!",
                "Que de bonheur!"
            ]
    },
]